# my global config
global:
  scrape_interval:     120s  # Intervalo global de recolección de métricas
  evaluation_interval: 120s  # Intervalo global de evaluación de reglas
  # scrape_timeout se deja con el valor predeterminado de 10s.

  # Etiquetas adicionales que se aplican a todas las series de tiempo.
  external_labels:
    monitor: 'mikrotik-monitoring'

# Configuración de alertas para conectarse con Alertmanager
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'  # Dirección del servicio Alertmanager en docker-compose

# Cargar y evaluar reglas de este archivo cada 'evaluation_interval' segundos.
rule_files:
  - "/etc/prometheus/rules/*.yml"  # Ruta a los archivos de reglas de alertas.

# Configuración de scraping (recolección) de métricas
scrape_configs:
  # Configuración para recolectar métricas del servicio 'mikrotik'
  - job_name: 'mikrotik'
    scrape_interval: 15s  # Sobrescribe el intervalo global solo para este job.
    static_configs:
      - targets:
        - 'mktxp:49090'  # El servicio que genera las métricas de Mikrotik.

  # Configuración para recolectar métricas de ping utilizando Blackbox Exporter
  - job_name: 'mikrotik_ping'
    scrape_interval: 30s  # Intervalo de scraping para las métricas de ping.
    metrics_path: /probe  # Ruta para realizar el ping.
    params:
      module: [icmp_ttl5]  # Protocolo ICMP para el ping.
    static_configs:
      - targets:
          - 192.168.0.20
          - 192.168.0.21
          - 192.168.0.22
    relabel_configs:
      # Renombrado de etiquetas para asociar IP con ubicaciones personalizadas
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115  # Dirección del Blackbox Exporter.

      # Reemplazo de etiquetas para asociar nombres más amigables a las IPs
      - source_labels: [__param_target]
        action: replace
        target_label: instance
        replacement: 'San Miguel'  # Renombra 192.168.0.21 como 'San Miguel'.
        regex: '192\\.168\\.0\\.20'

      - source_labels: [__param_target]
        action: replace
        target_label: instance
        replacement: 'Montenegro'  # Renombra 192.168.0.22 como 'Montenegro'.
        regex: '192\\.168\\.0\\.21'

      - source_labels: [__param_target]
        action: replace
        target_label: instance
        replacement: 'Calacoto'  # Renombra 192.168.0.23 como 'Calacoto'.
        regex: '192\\.168\\.0\\.22'


      